### ISSUE TITLE
Cavalcade service fails to start

### ISSUE THREAD

**Issue by nikolareljin** [humanmade/altis-local-server#431] opened 2022-02-21 21:09 UTC
When trying to run the containers with the command

`composer server`

the following containers fail to run:

```
ed12df1994b1   humanmade/altis-local-server-php:4.0.0-dev     "/usr/local/bin/cava…"   2 days ago   Restarting (1) 43 seconds ago     wsj-deloitte_cavalcade_1
```

When checking the error log of the service `composer server logs cavalcade`

```
Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wordpress.wp_cavalcade_jobs' doesn't exist
cavalcade_1        | #0 /etc/cavalcade/inc/class-runner.php(247): PDO->prepare('SELECT * FROM w...')
cavalcade_1        | #1 /etc/cavalcade/inc/class-runner.php(127): HM\Cavalcade\Runner\Runner->get_next_job()
cavalcade_1        | #2 /etc/cavalcade/bin/cavalcade(33): HM\Cavalcade\Runner\Runner->run()
cavalcade_1        | #3 {main}
...
```

**Source**

The following database was empty:

`wordpress` 

on the host `localhost`:

```
e0bb2d29e7fa   biarms/mysql:5.7     "/usr/local/bin/dock…"   2 hours ago   Up 2 hours (healthy)                    0.0.0.0:49235->3306/tcp, :::49235->3306/tcp   wsj-deloitte-db
```

Another potential improvement would be to have the ability to expose constant port for the DB (in the `./vendor/docker-compose.yml`).

**OS**
- Linux kernel 5.13.0-27-generic  29~20.04.1-Ubuntu

**Comment by roborourke** [comment] 2022-03-15 16:19
Was this this from a clean set up or was there any project specific code? This would most likely happen if there's a PHP fatal error occurring. If you can't replicate it with a clean install of Altis then the issue is probably elsewhere. It happens if a project has further setup steps or has code that tries to access the database too early before WP has installed.

**Comment by roborourke** [comment] 2022-05-03 09:22
Going to close this out as there seem to be no +1s or response so far. It's very likely this is not cavalcade specific and some PHP fatal error in the app prevented WP from installing. This can often be confirmed by running `composer server logs php`.

**Closed by roborourke** 2022-05-03 09:22 UTC
Labels: bug
