### ISSUE TITLE
Stack traces dumped out if Docker isn't running

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-local-server#401] opened 2021-12-18 13:22 UTC
Steps to reproduce:
1. Ensure Docker isn't running
2. Run `composer server start`

I expected a friendly message telling me Docker isn't running. However, instead I saw this:

<img width="805" alt="Screen Shot 2021-12-18 at 12 22 51@2x" src="https://user-images.githubusercontent.com/21655/146640952-30bd5661-9b21-491e-a4f7-28609e814107.png">

Acceptance criteria:

- [ ] Show a friendly message instead if docker isn't running

**Comment by robindevitt** [comment] 2022-01-10 10:00
This is the error message I see?
![Screenshot 2022-01-10 at 11.59.38.png](https://images.zenhubusercontent.com/615d863972ceea502ec6a54f/006004b7-f04c-4bca-8335-7a23619477a5)

**Comment by rmccue** [comment] 2022-01-10 14:15
Yeah, not sure exactly how it ends up in this state; in either case though, I think we should catch this earlier?

**Comment by roborourke** [comment] 2022-02-07 11:56
Duplicate of #268

**Closed by roborourke** 2022-02-07 11:56 UTC
Labels: bug, should have
