### ISSUE TITLE
Elasticsearch Warning message on install

### ISSUE THREAD

**Issue by pdewouters** [humanmade/altis-local-server#58] opened 2019-10-17 08:19 UTC
`Setting up ElasticPress...
Adding mapping...
Deleting index...
Warning: Error in ElasticPress request: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"sandboxsitealtisdev-1","index_uuid":"_na_","index":"sandboxsitealtisdev-1"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"sandboxsitealtisdev-1","index_uuid":"_na_","index":"sandboxsitealtisdev-1"},"status":404} (404) in /usr/src/app/vendor/altis/enhanced-search/inc/namespace.php on line 143
Success: Index deleted
Success: Mapping sent
Indexing posts...
Processed 3/3 entries. . .
Number of posts indexed on site 1: 3`

**Comment by rmccue** [comment] 2019-10-17 09:24
Duplicate of https://github.com/humanmade/altis-enhanced-search/issues/31

**Closed by rmccue** 2019-10-17 09:24 UTC
