### ISSUE TITLE
Add support to install wp-cli packages

### ISSUE THREAD

**Issue by ntwb** [humanmade/altis-local-server#118] opened 2020-01-28 09:30 UTC
When trying to install a wp-cli package this morning I encounted the following:

```shell
❯ composer server cli -- package install foo/bar
Error: Composer directory '/.wp-cli/packages' for packages couldn't 
be created: mkdir(): Permission denied
```

It would be great if this folder was created during setup, or made writable for the `cli` command to create on demand.

Aside: It would also be great to be able to define wp-cli packages in a projects `composer.json` file, though this might be out of scope for this issue

**Comment by roborourke** [comment] 2020-01-28 10:10
#112 might help with this, however I think it depends on how you're intending to use the package, for instance:

1. is it providing tooling you'll need on Vantage / sandbox server?
2. is it providing tooling others working on the project need?
3. is it just for your own purposes?

If the answer is 3 then supporting packages installed this way makes sense because they won't be supported or available in production. If the answer is 1 or 2 however then installing packages via WP CLI is the wrong approach.

--------------------

Going from the [commands cookbook here](https://make.wordpress.org/cli/handbook/commands-cookbook/#distribute-as-a-stand-alone-command) all command packages must autoload their main file.

The autoloading does introduce a potential issue, take [this usergen package](https://github.com/alessandrotesoro/wp-usergen-cli/blob/master/wp-usergen-cli.php) for instance. It doesn't check if the `WP_CLI` class exists and will cause things like `phpunit` or anything run from `vendor/bin` to break. [Good quality packages such this dotenv one](https://github.com/aaemnnosttv/wp-cli-dotenv-command/blob/master/command.php) however do check for this and are safe to install.

Provided the required package checks for the existence of `WP_CLI` there's generally no need to explicitly install and load packages using WP CLI via the `wp package` commands, the same packages can be required by composer directly using `composer require aaemnnosttv/wp-cli-dotenv-command` for example. If the package is not safe to autoload the recommendation is to make a PR or raise an issue with the maintainer, or failing that to fork the package until the problem is resolved.

You can [find most packages published to packagist here](
https://packagist.org/?type=wp-cli-package) (some won't have the `type` property set to `wp-cli-package` as it's not a hard requirement). If the package only exists as a github repo or similar you'll have to add it to the `repositories` section of your `composer.json` as you would for any other unpublished package.

**Comment by roborourke** [comment] 2020-01-28 10:13
I think this is at least worth documenting along with the basics of how to make a command. Depends on your answer regarding the use case as to whether this is something we should explicitly enable / set up in the docker image. That would require installing composer on the image too.

**Comment by ntwb** [comment] 2020-01-28 12:25
Thanks for the detailed reply, it was most definitely number 3 from the list, I simply wanted to test a wp-cli package on my local setup.

I'll test that by `composer require`'ing it

**Comment by roborourke** [comment] 2020-01-28 17:29
Are you happy for me to close this issue in favour of one like "Document installing & creating WP CLI packages" or similar? I think a guide probably makes sense for that.

If you feel like the `wp package` command should be supported we can look into that but it's a bit tricky as we use the same php container for local server as we do on production.

We could at least intercept it and indicate it's unsupported thinking about it.

**Closed** 2020-01-30 00:53 UTC
Labels: enhancement, help wanted
