### ISSUE TITLE
`composer server logs` does not work without a `<service>` parameter

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-server#270] opened 2021-03-09 14:27 UTC
The docs for the `composer server logs` command states "Tail the logs from a given service, defaults to php". This is not the case as the command triggers an error when no service is provided.

Steps to reproduce:

1. `composer server logs`
2. Observe the following error:

       [ErrorException]
       Undefined offset: 0

**Comment by rmccue** [comment] 2021-12-07 16:08
Duplicate of https://github.com/humanmade/altis-local-server/issues/216

**Closed by rmccue** 2021-12-07 16:08 UTC
Labels: bug
